# hugo.toml

baseURL = "https://johnsmusicandtech.com/"
languageCode = "en-us"
title = "John's Music & Tech"
theme = "PaperMod"
publishDir = "docs"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 10

[params]
  author = "John Sohn"
  ShowReadingTime = true
  ShowWordCount = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowShareButtons = false
  defaultTheme = "auto"

[taxonomies]
  tag = "tags"
  category = "categories"